name: Release(changelog)
on:
  workflow_dispatch:
    inputs:
      version:
        description: MAJOR.MINOR.PATCH version
        required: true
      branch:
        description: Branch to update
        default: main
        required: true

jobs:
  cut:
    runs-on: ubuntu-latest
    defaults:
      run:

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Set up correct version of node for use with release tooling
      - id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - uses: actions/setup-node@v1
        with: { node-version: '${{ steps.nvmrc.outputs.NODE_VERSION }}' }
      - run: yarn install
        working-directory: dev/release
      - run: yarn run build
        working-directory: dev/release

      # Add a new section "## $MAJOR.MINOR" to CHANGELOG.md immediately under
      # "## Unreleased changes". Add new empty sections under "## Unreleased changes".
      - run: yarn run release changelog:cut ${{ github.event.inputs.version }}
        working-directory: dev/release
      # Commit CHANGELOG update to base branch
      - name: Open pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ github.event.inputs.branch }}
          branch: release-changelog-${{ github.event.inputs.branch }}
          title: 'Cut ${{ github.event.inputs.version }} changelog from ${{ github.event.inputs.branch }}'
          commit-message: 'Cut ${{ github.event.inputs.version }} changelog from ${{ github.event.inputs.branch }}'
          body: |
            This pull request was generated by [this run](https://github.com/sourcegraph/deploy-sourcegraph/actions/runs/${{ github.run_id }}).
